// Code generated by "enumer -type Compressor -trimprefix Compressor_"; DO NOT EDIT.

package udp

import (
	"fmt"
)

const _CompressorName = "NONEZSTD"

var _CompressorIndex = [...]uint8{0, 4, 8}

func (i Compressor) String() string {
	if i < 0 || i >= Compressor(len(_CompressorIndex)-1) {
		return fmt.Sprintf("Compressor(%d)", i)
	}
	return _CompressorName[_CompressorIndex[i]:_CompressorIndex[i+1]]
}

var _CompressorValues = []Compressor{0, 1}

var _CompressorNameToValueMap = map[string]Compressor{
	_CompressorName[0:4]: 0,
	_CompressorName[4:8]: 1,
}

// CompressorString retrieves an enum value from the enum constants string name.
// Throws an error if the param is not part of the enum.
func CompressorString(s string) (Compressor, error) {
	if val, ok := _CompressorNameToValueMap[s]; ok {
		return val, nil
	}
	return 0, fmt.Errorf("%s does not belong to Compressor values", s)
}

// CompressorValues returns all values of the enum
func CompressorValues() []Compressor {
	return _CompressorValues
}

// IsACompressor returns "true" if the value is listed in the enum definition. "false" otherwise
func (i Compressor) IsACompressor() bool {
	for _, v := range _CompressorValues {
		if i == v {
			return true
		}
	}
	return false
}
