// Code generated by "enumer -type Parser -trimprefix Parser_"; DO NOT EDIT.

package udp

import (
	"fmt"
)

const _ParserName = "NONEJSONPROTOBUF"

var _ParserIndex = [...]uint8{0, 4, 8, 16}

func (i Parser) String() string {
	if i < 0 || i >= Parser(len(_ParserIndex)-1) {
		return fmt.Sprintf("Parser(%d)", i)
	}
	return _ParserName[_ParserIndex[i]:_ParserIndex[i+1]]
}

var _ParserValues = []Parser{0, 1, 2}

var _ParserNameToValueMap = map[string]Parser{
	_ParserName[0:4]:  0,
	_ParserName[4:8]:  1,
	_ParserName[8:16]: 2,
}

// ParserString retrieves an enum value from the enum constants string name.
// Throws an error if the param is not part of the enum.
func ParserString(s string) (Parser, error) {
	if val, ok := _ParserNameToValueMap[s]; ok {
		return val, nil
	}
	return 0, fmt.Errorf("%s does not belong to Parser values", s)
}

// ParserValues returns all values of the enum
func ParserValues() []Parser {
	return _ParserValues
}

// IsAParser returns "true" if the value is listed in the enum definition. "false" otherwise
func (i Parser) IsAParser() bool {
	for _, v := range _ParserValues {
		if i == v {
			return true
		}
	}
	return false
}
