// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package crypter

import (
	mock "github.com/stretchr/testify/mock"
)

// NewMockCrypter creates a new instance of MockCrypter. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockCrypter(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockCrypter {
	mock := &MockCrypter{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockCrypter is an autogenerated mock type for the Crypter type
type MockCrypter struct {
	mock.Mock
}

type MockCrypter_Expecter struct {
	mock *mock.Mock
}

func (_m *MockCrypter) EXPECT() *MockCrypter_Expecter {
	return &MockCrypter_Expecter{mock: &_m.Mock}
}

// DeCrypt provides a mock function for the type MockCrypter
func (_mock *MockCrypter) DeCrypt(cipherText []byte) ([]byte, error) {
	ret := _mock.Called(cipherText)

	if len(ret) == 0 {
		panic("no return value specified for DeCrypt")
	}

	var r0 []byte
	var r1 error
	if returnFunc, ok := ret.Get(0).(func([]byte) ([]byte, error)); ok {
		return returnFunc(cipherText)
	}
	if returnFunc, ok := ret.Get(0).(func([]byte) []byte); ok {
		r0 = returnFunc(cipherText)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]byte)
		}
	}
	if returnFunc, ok := ret.Get(1).(func([]byte) error); ok {
		r1 = returnFunc(cipherText)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockCrypter_DeCrypt_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeCrypt'
type MockCrypter_DeCrypt_Call struct {
	*mock.Call
}

// DeCrypt is a helper method to define mock.On call
//   - cipherText []byte
func (_e *MockCrypter_Expecter) DeCrypt(cipherText interface{}) *MockCrypter_DeCrypt_Call {
	return &MockCrypter_DeCrypt_Call{Call: _e.mock.On("DeCrypt", cipherText)}
}

func (_c *MockCrypter_DeCrypt_Call) Run(run func(cipherText []byte)) *MockCrypter_DeCrypt_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 []byte
		if args[0] != nil {
			arg0 = args[0].([]byte)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockCrypter_DeCrypt_Call) Return(bytes []byte, err error) *MockCrypter_DeCrypt_Call {
	_c.Call.Return(bytes, err)
	return _c
}

func (_c *MockCrypter_DeCrypt_Call) RunAndReturn(run func(cipherText []byte) ([]byte, error)) *MockCrypter_DeCrypt_Call {
	_c.Call.Return(run)
	return _c
}

// EnCrypt provides a mock function for the type MockCrypter
func (_mock *MockCrypter) EnCrypt(plainText []byte) ([]byte, error) {
	ret := _mock.Called(plainText)

	if len(ret) == 0 {
		panic("no return value specified for EnCrypt")
	}

	var r0 []byte
	var r1 error
	if returnFunc, ok := ret.Get(0).(func([]byte) ([]byte, error)); ok {
		return returnFunc(plainText)
	}
	if returnFunc, ok := ret.Get(0).(func([]byte) []byte); ok {
		r0 = returnFunc(plainText)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]byte)
		}
	}
	if returnFunc, ok := ret.Get(1).(func([]byte) error); ok {
		r1 = returnFunc(plainText)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockCrypter_EnCrypt_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'EnCrypt'
type MockCrypter_EnCrypt_Call struct {
	*mock.Call
}

// EnCrypt is a helper method to define mock.On call
//   - plainText []byte
func (_e *MockCrypter_Expecter) EnCrypt(plainText interface{}) *MockCrypter_EnCrypt_Call {
	return &MockCrypter_EnCrypt_Call{Call: _e.mock.On("EnCrypt", plainText)}
}

func (_c *MockCrypter_EnCrypt_Call) Run(run func(plainText []byte)) *MockCrypter_EnCrypt_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 []byte
		if args[0] != nil {
			arg0 = args[0].([]byte)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockCrypter_EnCrypt_Call) Return(bytes []byte, err error) *MockCrypter_EnCrypt_Call {
	_c.Call.Return(bytes, err)
	return _c
}

func (_c *MockCrypter_EnCrypt_Call) RunAndReturn(run func(plainText []byte) ([]byte, error)) *MockCrypter_EnCrypt_Call {
	_c.Call.Return(run)
	return _c
}
