// Code generated by mockery v0.0.0-dev. DO NOT EDIT.

package mocks

import (
	mock "github.com/stretchr/testify/mock"
	protoiface "google.golang.org/protobuf/runtime/protoiface"
	"valley-pkg/tcp"
)

// Conn is an autogenerated mock type for the Conn type
type Conn struct {
	mock.Mock
}

// ReadMessage provides a mock function with given fields:
func (_m *Conn) ReadMessage() (*tcp.Message, error) {
	ret := _m.Called()

	var r0 *tcp.Message
	if rf, ok := ret.Get(0).(func() *tcp.Message); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*tcp.Message)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// SetCompressor provides a mock function with given fields: compressor
func (_m *Conn) SetCompressor(compressor tcp.Compressor) {
	_m.Called(compressor)
}

// SetParser provides a mock function with given fields: parser
func (_m *Conn) SetParser(parser tcp.Parser) {
	_m.Called(parser)
}

// WriteMessage provides a mock function with given fields: kind, m
func (_m *Conn) WriteMessage(kind int8, m protoiface.MessageV1) error {
	ret := _m.Called(kind, m)

	var r0 error
	if rf, ok := ret.Get(0).(func(int8, protoiface.MessageV1) error); ok {
		r0 = rf(kind, m)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
