// Code generated by "enumer -type CompressorType -json"; DO NOT EDIT.

package tcp

import (
	"encoding/json"
	"fmt"
	"strings"
)

const _CompressorTypeName = "NoneZSTD"

var _CompressorTypeIndex = [...]uint8{0, 4, 8}

const _CompressorTypeLowerName = "nonezstd"

func (i CompressorType) String() string {
	i -= 1
	if i < 0 || i >= CompressorType(len(_CompressorTypeIndex)-1) {
		return fmt.Sprintf("CompressorType(%d)", i+1)
	}
	return _CompressorTypeName[_CompressorTypeIndex[i]:_CompressorTypeIndex[i+1]]
}

// An "invalid array index" compiler error signifies that the constant values have changed.
// Re-run the stringer command to generate them again.
func _CompressorTypeNoOp() {
	var x [1]struct{}
	_ = x[None-(1)]
	_ = x[ZSTD-(2)]
}

var _CompressorTypeValues = []CompressorType{None, ZSTD}

var _CompressorTypeNameToValueMap = map[string]CompressorType{
	_CompressorTypeName[0:4]:      None,
	_CompressorTypeLowerName[0:4]: None,
	_CompressorTypeName[4:8]:      ZSTD,
	_CompressorTypeLowerName[4:8]: ZSTD,
}

var _CompressorTypeNames = []string{
	_CompressorTypeName[0:4],
	_CompressorTypeName[4:8],
}

// CompressorTypeString retrieves an enum value from the enum constants string name.
// Throws an error if the param is not part of the enum.
func CompressorTypeString(s string) (CompressorType, error) {
	if val, ok := _CompressorTypeNameToValueMap[s]; ok {
		return val, nil
	}

	if val, ok := _CompressorTypeNameToValueMap[strings.ToLower(s)]; ok {
		return val, nil
	}
	return 0, fmt.Errorf("%s does not belong to CompressorType values", s)
}

// CompressorTypeValues returns all values of the enum
func CompressorTypeValues() []CompressorType {
	return _CompressorTypeValues
}

// CompressorTypeStrings returns a slice of all String values of the enum
func CompressorTypeStrings() []string {
	strs := make([]string, len(_CompressorTypeNames))
	copy(strs, _CompressorTypeNames)
	return strs
}

// IsACompressorType returns "true" if the value is listed in the enum definition. "false" otherwise
func (i CompressorType) IsACompressorType() bool {
	for _, v := range _CompressorTypeValues {
		if i == v {
			return true
		}
	}
	return false
}

// MarshalJSON implements the json.Marshaler interface for CompressorType
func (i CompressorType) MarshalJSON() ([]byte, error) {
	return json.Marshal(i.String())
}

// UnmarshalJSON implements the json.Unmarshaler interface for CompressorType
func (i *CompressorType) UnmarshalJSON(data []byte) error {
	var s string
	if err := json.Unmarshal(data, &s); err != nil {
		return fmt.Errorf("CompressorType should be a string, got %s", data)
	}

	var err error
	*i, err = CompressorTypeString(s)
	return err
}
