// Code generated by "enumer -type ParserType -json"; DO NOT EDIT.

package tcp

import (
	"encoding/json"
	"fmt"
	"strings"
)

const _ParserTypeName = "JSONPROTOBUF"

var _ParserTypeIndex = [...]uint8{0, 4, 12}

const _ParserTypeLowerName = "jsonprotobuf"

func (i ParserType) String() string {
	i -= 1
	if i < 0 || i >= ParserType(len(_ParserTypeIndex)-1) {
		return fmt.Sprintf("ParserType(%d)", i+1)
	}
	return _ParserTypeName[_ParserTypeIndex[i]:_ParserTypeIndex[i+1]]
}

// An "invalid array index" compiler error signifies that the constant values have changed.
// Re-run the stringer command to generate them again.
func _ParserTypeNoOp() {
	var x [1]struct{}
	_ = x[JSON-(1)]
	_ = x[PROTOBUF-(2)]
}

var _ParserTypeValues = []ParserType{JSON, PROTOBUF}

var _ParserTypeNameToValueMap = map[string]ParserType{
	_ParserTypeName[0:4]:       JSON,
	_ParserTypeLowerName[0:4]:  JSON,
	_ParserTypeName[4:12]:      PROTOBUF,
	_ParserTypeLowerName[4:12]: PROTOBUF,
}

var _ParserTypeNames = []string{
	_ParserTypeName[0:4],
	_ParserTypeName[4:12],
}

// ParserTypeString retrieves an enum value from the enum constants string name.
// Throws an error if the param is not part of the enum.
func ParserTypeString(s string) (ParserType, error) {
	if val, ok := _ParserTypeNameToValueMap[s]; ok {
		return val, nil
	}

	if val, ok := _ParserTypeNameToValueMap[strings.ToLower(s)]; ok {
		return val, nil
	}
	return 0, fmt.Errorf("%s does not belong to ParserType values", s)
}

// ParserTypeValues returns all values of the enum
func ParserTypeValues() []ParserType {
	return _ParserTypeValues
}

// ParserTypeStrings returns a slice of all String values of the enum
func ParserTypeStrings() []string {
	strs := make([]string, len(_ParserTypeNames))
	copy(strs, _ParserTypeNames)
	return strs
}

// IsAParserType returns "true" if the value is listed in the enum definition. "false" otherwise
func (i ParserType) IsAParserType() bool {
	for _, v := range _ParserTypeValues {
		if i == v {
			return true
		}
	}
	return false
}

// MarshalJSON implements the json.Marshaler interface for ParserType
func (i ParserType) MarshalJSON() ([]byte, error) {
	return json.Marshal(i.String())
}

// UnmarshalJSON implements the json.Unmarshaler interface for ParserType
func (i *ParserType) UnmarshalJSON(data []byte) error {
	var s string
	if err := json.Unmarshal(data, &s); err != nil {
		return fmt.Errorf("ParserType should be a string, got %s", data)
	}

	var err error
	*i, err = ParserTypeString(s)
	return err
}
